import { mkdtempSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterAll, describe, expect, it } from "vitest";
import { buildIndex } from "@mendpoint/codebase-index";
import type { ImpactableSurface } from "@mendpoint/shared";
import {
  analyzeImpact,
  discoverCandidates,
  detectGeneratedFiles,
  isGeneratedFile,
  sdkContextFromSurfaces,
} from "./index.js";

const tmpDirs: string[] = [];
function makeRepo(files: Record<string, string>): string {
  const dir = mkdtempSync(join(tmpdir(), "restraint-"));
  tmpDirs.push(dir);
  writeFileSync(join(dir, "package.json"), JSON.stringify({ name: "consumer" }), "utf8");
  for (const [rel, content] of Object.entries(files)) {
    const abs = join(dir, rel);
    mkdirSync(join(abs, ".."), { recursive: true });
    writeFileSync(abs, content, "utf8");
  }
  return dir;
}

afterAll(() => {
  for (const dir of tmpDirs) rmSync(dir, { recursive: true, force: true });
});

const GEN_HEADER =
  "/**\n * AUTO-GENERATED - DO NOT EDIT.\n * Generated by OpenAPI Generator (https://openapi-generator.tech).\n */\n";

function renameSurfaces(): ImpactableSurface[] {
  return [
    {
      id: "s0",
      canonicalId: "acme.POST./charges.request_field_renamed.source.payment_method",
      kind: "request_field",
      op: "request_field_renamed",
      path: "/charges",
      method: "post",
      field: "payment_method",
      fromField: "source",
      toField: "payment_method",
      severity: "breaking",
      migrationStrategy: "Rename source → payment_method",
      explanation: "renamed",
      searchTokens: ["/charges", "source", "payment_method", "charges"],
    },
  ];
}

function ambiguousSurfaces(): ImpactableSurface[] {
  return [
    {
      id: "a0",
      canonicalId: "acme.POST./charges.request_field_ambiguous.source",
      kind: "request_field",
      op: "request_field_ambiguous",
      path: "/charges",
      method: "post",
      field: "source",
      fromField: "source",
      candidates: ["payment_method", "payment_source"],
      severity: "breaking",
      migrationStrategy: "human decision required",
      explanation: "source splits into payment_method or payment_source at runtime",
      searchTokens: ["/charges", "source", "charges"],
    },
  ];
}

describe("generated-file detection keys on header/marker, not path", () => {
  it("detects a file by AUTO-GENERATED header even at a non-generated path", () => {
    const dir = makeRepo({
      "src/handmade/looks_normal.js": `${GEN_HEADER}export const x = 1;\n`,
    });
    expect(isGeneratedFile(dir, "src/handmade/looks_normal.js", new Set())).toBe(true);
  });

  it("does NOT treat a hand-written file as generated just because its path contains 'generated'", () => {
    const dir = makeRepo({
      "src/generated/handwritten.js": "// hand maintained\nexport const y = 2;\n",
    });
    expect(isGeneratedFile(dir, "src/generated/handwritten.js", new Set())).toBe(false);
  });

  it("detects files listed in an openapi-generator FILES manifest", () => {
    const dir = makeRepo({
      ".openapi-generator/FILES": "src/api/Thing.js\n",
      "src/api/Thing.js": "export class Thing {}\n",
    });
    const generated = detectGeneratedFiles(buildIndex(dir));
    expect(generated.has("src/api/Thing.js")).toBe(true);
  });
});

describe("generated code is excluded from findings but surfaced separately", () => {
  it("generated files go to generatedReferences; hand-written files stay confident sites", async () => {
    const dir = makeRepo({
      "src/handwritten/charges.js":
        'import { ChargesApi } from "acme-sdk";\nexport function pay({ source }) {\n  return new ChargesApi().create({ source });\n}\n',
      "src/generated/model/Charge.js": `${GEN_HEADER}import { base } from "acme-sdk";\nexport class Charge {\n  constructor(data) {\n    this.source = data.source;\n  }\n}\n`,
    });

    const report = await analyzeImpact(dir, renameSurfaces(), {
      useLlm: false,
      minConfidence: "medium",
    });
    const sitePaths = report.sites.map((s) => s.filePath);
    const genPaths = (report.generatedReferences ?? []).map((g) => g.filePath);
    const lowPaths = report.lowConfidenceNotifications.map((s) => s.filePath);

    expect(sitePaths).toContain("src/handwritten/charges.js");
    expect(sitePaths).not.toContain("src/generated/model/Charge.js");
    // Not silently dropped: it appears under the generated outcome...
    expect(genPaths).toContain("src/generated/model/Charge.js");
    // ...and not smuggled into the low-confidence bucket either.
    expect(lowPaths).not.toContain("src/generated/model/Charge.js");
  });
});

describe("ambiguous changes abstain from confident findings", () => {
  it("emits no sites and reports the ambiguity as its own outcome", async () => {
    const dir = makeRepo({
      "src/charge.js":
        'import { ChargesApi } from "acme-sdk";\nexport function createCharge({ source, kind }) {\n  return new ChargesApi().create({ source });\n}\n',
    });

    const report = await analyzeImpact(dir, ambiguousSurfaces(), {
      useLlm: false,
      minConfidence: "medium",
    });

    expect(report.sites).toHaveLength(0);
    expect(report.lowConfidenceNotifications).toHaveLength(0);
    expect(report.ambiguousChanges ?? []).toHaveLength(1);
    expect(report.ambiguousChanges![0]!.fromField).toBe("source");
    expect(report.ambiguousChanges![0]!.candidates).toEqual(
      expect.arrayContaining(["payment_method", "payment_source"]),
    );
  });
});

describe("import expansion no longer matches every importing file", () => {
  it("a file importing an unrelated package gets no import_expansion candidate", () => {
    const dir = makeRepo({
      "src/noise.js": 'import _ from "lodash";\nexport const noop = () => _.identity(1);\n',
      "src/vendor.js": 'import c from "charges-client";\nexport const go = () => c.run();\n',
    });
    const index = buildIndex(dir, {
      sdkContext: sdkContextFromSurfaces(renameSurfaces()),
    });
    const candidates = discoverCandidates(index, renameSurfaces());

    const noiseImportExp = candidates.some(
      (c) => c.filePath === "src/noise.js" && c.sources.includes("import_expansion"),
    );
    expect(noiseImportExp).toBe(false);

    // The fragment match is real, not vacuous: an import that actually contains a
    // change token ("charges") is still recognised.
    const vendorImportExp = candidates.some(
      (c) => c.filePath === "src/vendor.js" && c.sources.includes("import_expansion"),
    );
    expect(vendorImportExp).toBe(true);
  });
});
