export { RELEASE, releaseBanner, type ReleaseInfo } from "./release.js";
export {
  nodeEnv,
  isProduction,
  deploymentProfile,
  validateApiEnv,
  assertApiEnvOrExit,
  type EnvReport,
  type DeploymentProfile,
} from "./env.js";
export {
  rateLimit,
  rateLimitKeyFromRequest,
  clearRateLimits,
  rateLimitBucketCount,
  type RateLimitResult,
  type RateLimitOpts,
} from "./rate-limit.js";
export {
  tenantQuota,
  clearTenantQuotas,
  tenantQuotaBucketCount,
  type TenantQuotaResult,
  type TenantQuotaOpts,
} from "./tenant-quota.js";
export {
  isFeatureEnabled,
  featureMatrix,
  assertGaOnly,
  type FeatureId,
} from "./features.js";
export {
  TRANSFORMER_GATE_SCHEMA_VERSION,
  TRANSFORMER_GATE_BOUNDARIES,
  parseTransformerGateConfig,
  assessTransformerGate,
  authorizeTransformerWorkerAction,
  authorizeTransformerDelivery,
  type TransformerGateBoundary,
  type TransformerGateGrant,
  type TransformerGateConfig,
  type TransformerGateInput,
  type TransformerGateDecision,
} from "./transformer-gate.js";
export {
  TRANSFORMER_CANARY_ACCEPTANCE_EVIDENCE_REF,
  PILOT_SAMPLE_TENANT_ID,
  PILOT_SAMPLE_ENVIRONMENT,
  PILOT_SAMPLE_DELIVERY_APPROVAL_REF,
  generatePilotTransformerGateConfig,
  serializePilotTransformerGateConfig,
  samplePilotTransformerGateConfig,
  type PilotTransformerEnablementOptions,
} from "./transformer-enablement.js";
export { liveness, readiness, type ProbeResult } from "./readiness.js";
export {
  DISASTER_RECOVERY_POLICY_SCHEMA_VERSION,
  BACKUP_MANIFEST_SCHEMA_VERSION,
  RECOVERY_DRILL_REPORT_SCHEMA_VERSION,
  LAST_VERIFIED_BACKUP_EVIDENCE_SCHEMA_VERSION,
  OBJECT_BACKUP_COMMIT_SCHEMA_VERSION,
  OBJECT_BACKUP_RECOVERY_RECEIPT_SCHEMA_VERSION,
  CORE_DISASTER_RECOVERY_POLICY,
  createBackupBundle,
  createApplicationConsistentBackup,
  customerBackupInputFromEnv,
  validateCustomerBackupPathSafety,
  validateCustomerRestorePathSafety,
  parseCustomerBackupKey,
  prepareMutationFenceDirectories,
  prepareCustomerBackupDirectories,
  inspectMutationFence,
  recoverStaleMutationMarker,
  createLastVerifiedBackupEvidence,
  recordLastVerifiedBackupEvidence,
  loadAuthenticatedLastVerifiedBackupEvidence,
  verifyAuthenticatedLastVerifiedBackupEvidence,
  createObjectBackupCommit,
  verifyObjectBackupCommit,
  createObjectBackupRecoveryReceipt,
  verifyObjectBackupRecoveryReceipt,
  assessCustomerBackupReadiness,
  loadAuthenticatedBackupManifest,
  isBackupFenceActive,
  resolveMutationFenceRoot,
  tryAcquireMutationLease,
  initializeWithMutationLease,
  verifyBackupBundle,
  restoreBackupAtomically,
  runIsolatedRecoveryDrill,
  verifyRecoveryDrillReport,
  assessRecoveryDrillCadence,
  type RecoveryResourceKind,
  type SqliteRecoveryResourceKind,
  type DisasterRecoveryPolicy,
  type BackupResourceManifest,
  type BackupManifest,
  type BackupEncryptedFileManifest,
  type LastVerifiedBackupEvidence,
  type ObjectBackupCommit,
  type ObjectBackupRecoveryReceipt,
  type ObjectBackupPublication,
  type InspectedFenceMarker,
  type RecoveryDrillReport,
  type MutationLease,
  type ApplicationConsistentBackupInput,
} from "./disaster-recovery.js";
export {
  isTelemetryEnabled,
  telemetryEndpoint,
  startSpan,
  withSpan,
  recordCounter,
  recordHistogram,
  flushTelemetry,
  drainTelemetry,
  resetTelemetry,
  type TelemetrySpan,
  type TelemetryAttributes,
  type TelemetrySpanStatus,
  type TelemetryTransport,
  type FlushTelemetryResult,
} from "./telemetry.js";
export {
  MEASURED_DR_DRILL_SCHEMA_VERSION,
  measureRestoreDrill,
  runMeasuredDrDrill,
  verifyMeasuredDrillResult,
  writeMeasuredDrillResult,
  type MeasuredDrillResult,
  type DrillCanaryResult,
  type MeasureRestoreDrillInput,
  type RunMeasuredDrDrillInput,
} from "./dr-drill.js";
export {
  VPC_DEPLOYMENT_CONTRACT_VERSION,
  assessVpcDeployment,
  type VpcDeploymentContract,
  type VpcDeploymentAssessment,
} from "./vpc-deployment.js";

export {
  SERVICE_HEALTH_SCHEMA_VERSION,
  CORRELATION_BOUNDARIES,
  createCorrelationContext,
  childCorrelationContext,
  verifyCorrelationCoverage,
  assessServiceHealth,
  verifyServiceHealthEvidence,
  SLO_SCHEMA_VERSION,
  DEFAULT_SLO_TARGETS,
  availabilitySignal,
  jobSuccessSignal,
  latencySignal,
  evaluateSlo,
  evaluateSloReport,
  verifySloReport,
  type CorrelationBoundary,
  type CorrelationContext,
  type CorrelatedBoundaryEvidence,
  type ErrorBudgetPolicy,
  type ServiceWindow,
  type ServiceHealthEvidence,
  type SloName,
  type SloBurnState,
  type SloTarget,
  type SloSignal,
  type SloEvidence,
  type SloReport,
} from "./service-health.js";
