import { createHash, generateKeyPairSync, sign } from "node:crypto";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createDb, insertArtifactManifest, insertEvidenceRecord, insertPrincipal, type AppDb } from "@mendpoint/db";
import { postTrainedReconciliationResultDigest } from "@mendpoint/pipeline";
import type { AdapterLifecycleRecord, ExecutorDescriptor, PostTrainedConsentSnapshot } from "@mendpoint/platform";
import { Hono } from "hono";
import { afterEach, describe, expect, it } from "vitest";
import type { ApiEnv } from "./auth.js";
import { advancedAiAttestationCryptoFromEnv, advancedAiTrainingRuntimeFromEnv, createAdvancedAiApplicationRoutes, createDurableAttestationScopeAuthority, createDurablePostTrainedEvidenceAuthority } from "./advanced-ai-applications.js";

const dirs: string[] = []; const dbs: AppDb[] = [];
afterEach(() => { dbs.splice(0).forEach((db) => db.raw.close()); dirs.splice(0).forEach((dir) => rmSync(dir, { recursive: true, force: true })); });
const now = "2026-08-12T12:00:00.000Z"; const DIGEST = `sha256:${"a".repeat(64)}`; const ROLLBACK = `sha256:${"b".repeat(64)}`;
function lifecycle(): AdapterLifecycleRecord { return { tenantId: "tenant-a", adapterId: "adapter-1", state: "monitored", revision: 7, baseModel: { modelId: "base-1", license: "commercial", evidenceRef: "evidence://base" }, artifactDigest: DIGEST, trainingDataset: { datasetId: "dataset-1", lineageRefs: ["lineage://1"], consent: { status: "granted", evidenceRefs: ["consent://train"] }, sufficiency: { representative: true, sampleCount: 1000, minimumSampleCount: 500, evidenceRefs: ["eval://data"] } }, heldOutEvaluation: { reportRef: "eval://held", passed: true, successRate: .96, regressionRate: .01 }, promotionThresholds: { minimumSuccessRate: .9, maximumRegressionRate: .02 }, approvedInfrastructure: { approved: true, marker: "gpu-a", evidenceRef: "infra://approved" }, servingRevision: "serve-7", monitoringWindow: { startsAt: "2026-08-01T00:00:00.000Z", endsAt: "2026-09-01T00:00:00.000Z" }, rollbackTarget: { servingRevision: "serve-6", artifactDigest: ROLLBACK }, approver: { principalId: "human", approvedAt: "2026-08-01T00:00:00.000Z", evidenceRef: "approval://1" }, canaryEvidence: { passed: true, observedAt: "2026-08-01T00:00:00.000Z", evidenceRefs: ["canary://1"] }, evidenceRefs: ["lifecycle://7"], history: [{ revision: 7, from: "promoted", to: "monitored", actorId: "actor", occurredAt: "2026-08-02T00:00:00.000Z", evidenceRefs: ["monitor://1"] }] }; }
function consent(): PostTrainedConsentSnapshot { return { tenantId: "tenant-a", datasetId: "dataset-1", revision: 3, status: "active", evidenceRefs: ["consent://runtime"], checkedAt: "2026-08-12T11:59:00.000Z" }; }
function descriptor(): ExecutorDescriptor { return { executorId: "executor-1", providerId: "internal", kind: "adapter", version: "serve-7", deployment: "internal", capabilities: ["repair"], tools: ["repo-read"], regions: ["us-east"], price: { version: "p1", currency: "USD", effectiveAt: "2026-08-01T00:00:00.000Z" }, limits: { maximumInputTokens: 4000, maximumOutputTokens: 2000, maximumConcurrentTasks: 2 }, health: { status: "healthy", checkedAt: "2026-08-12T11:58:00.000Z", evidenceRef: "health://1" }, license: { id: "commercial", commercialUse: true, redistribution: "restricted" }, maximumDataClassification: "internal", maximumRisk: "medium", qualityScore: .95, estimatedLatencyMs: 1000, estimatedCostUsd: .2 }; }
function task() { return { taskId: "task-1", tenantId: "tenant-a", kind: "repair", goal: "Repair", idempotencyKey: "task-idem", inputArtifactIds: ["input"], requiredCapabilities: ["repair"], allowedTools: ["repo-read"], context: { estimatedInputTokens: 1000, maximumOutputTokens: 500 }, verification: { requiredChecks: ["tests"], requireAll: true, onFailure: "human_handoff" }, fallbackPolicy: { enabled: false, maxAttempts: 1, sameExecutorRetries: 0, retryableFailures: [], fallbackFailures: [] }, privacy: { classification: "internal", requiredRegion: "us-east" }, risk: "medium", quality: { minimumScore: .8 }, latency: { maximumMs: 5000 }, budget: { maximumUsd: 1 } }; }
function policy() { return { snapshotId: "policy-1", version: 1, capturedAt: "2026-08-12T11:00:00.000Z", privacy: { allowedClassifications: ["internal"], externalProcessingAllowed: false }, region: { allowedExecutionRegions: ["us-east"] }, risk: { maximumAutonomousRisk: "medium", humanReviewAtOrAbove: "critical" }, quality: { minimumScore: .8 }, latency: { maximumMs: 5000 }, budget: { maximumUsd: 1 } }; }
function fixture(enabled = true) { const dir = mkdtempSync(join(tmpdir(), "advanced-ai-api-")); dirs.push(dir); const db = createDb(join(dir, "db.sqlite")); dbs.push(db); insertPrincipal(db, { id: "actor", tenantId: "tenant-a", kind: "service", subject: "actor", displayName: "Actor", createdAt: now }); const keys = generateKeyPairSync("ed25519"); const app = new Hono<ApiEnv>(); app.use("*", async (c, next) => { c.set("principal", { id: "public-actor", tenantId: c.req.header("x-tenant") ?? "tenant-a", role: (c.req.header("x-role") ?? "admin") as "admin" }); c.set("trustPrincipalId", "actor"); c.set("requestId", "request-1"); await next(); }); app.route("/advanced-ai", createAdvancedAiApplicationRoutes({ db, enabled, now: () => now, authorizeAttestationScope: () => true, authorizeDataset: () => true, signer: { keyId: "key-1", algorithm: "ed25519", sign: (bytes) => new Uint8Array(sign(null, bytes, keys.privateKey)) }, trustPolicy: { resolve: () => ({ keyId: "key-1", algorithm: "ed25519", publicKey: keys.publicKey, principalId: "actor", service: "mendpoint-attestation", tenantIds: ["tenant-a"], predicateTypes: ["https://mendpoint.ai/attestations/software/v1"], validFrom: "2026-08-01T00:00:00.000Z", validUntil: "2026-09-01T00:00:00.000Z", revokedAt: null }) }, attestationPrincipalId: "actor", readConsent: (_t, _d, stored) => stored, verifyEvidence: () => true, trainingWorkerId: "api-worker", trainingTimeoutMs: 1000, trainingLeaseMs: 5000, verifyReconciliation: (receipt) => receipt.signature === "test-signature", trainer: { train: async (request) => { const result = { status: "completed" as const, adapterBase64: Buffer.from(`local:${request.requestDigest}`).toString("base64"), evaluation: { passed: true, successRate: .95, regressionRate: .01, reportRef: "evaluation://local" }, canary: { passed: true, observedAt: now, evidenceRefs: ["canary://local"] }, evidenceRefs: ["training://local"], completedAt: now }; return { result, receipt: { tenantId: request.tenantId, jobId: request.jobId, requestDigest: request.requestDigest, leaseGeneration: request.leaseGeneration, outcome: result.status, resultDigest: postTrainedReconciliationResultDigest(result), observedAt: now, signature: "test-signature" } }; }, reconcile: async (request) => { const result = { status: "pending" as const }; return { result, receipt: { tenantId: request.tenantId, jobId: request.jobId, requestDigest: request.requestDigest, leaseGeneration: request.leaseGeneration, outcome: result.status, resultDigest: postTrainedReconciliationResultDigest(result), observedAt: now, signature: "test-signature" } }; } } })); return { app, db }; }
function add(db: AppDb, id: string, kind = id) { const content = JSON.stringify(kind === "learning_dataset_corpus" ? { id, samples: [{ input: "a", output: "b" }] } : { id }); const digest = createHash("sha256").update(content).digest("hex"); insertArtifactManifest(db, { id, tenantId: "tenant-a", kind, schemaVersion: 1, sha256: digest, mediaType: "application/json", sizeBytes: Buffer.byteLength(content), storageRef: `sqlite://${id}`, content, producerPrincipalId: "actor", createdAt: now }); }

describe("advanced AI applications API", () => {
  it("fails closed when durable attestation evidence cannot prove a passing post-edit verification", () => {
    const { db } = fixture();
    const authorized = createDurableAttestationScopeAuthority()(db, {
      tenantId: "tenant-a", repositoryId: "repo", runId: "run", correlationId: "corr",
      actorPrincipalId: "actor", idempotencyKey: "attest-baseline", outcome: "passed",
      issuedAt: now, artifacts: { sourceIds: [], snapshotId: "snapshot", candidateId: "candidate", verificationIds: [], policyId: "policy", deliveryId: null, rollbackId: null, waiverId: null },
    }, {
      tenantId: "tenant-a", repositoryId: "repo", runId: "run", correlationId: "corr",
      sourceArtifacts: [], snapshotArtifact: { artifactId: "snapshot", sha256: "a".repeat(64) },
      candidateArtifact: { artifactId: "candidate", sha256: "b".repeat(64) }, verificationArtifacts: [],
      policyArtifact: { artifactId: "policy", sha256: "c".repeat(64) }, deliveryArtifact: null,
      rollbackArtifact: null, waiverArtifact: null,
    });
    expect(authorized).toBe(false);
  });
  it("is production default off", async () => { const { app } = fixture(false); expect((await app.request("/advanced-ai/attestations/a")).status).toBe(404); expect((await app.request("/advanced-ai/post-trained/adapters/a")).status).toBe(404); });
  it("constructs signer and trust only from a matching injected key pair", async () => { const keys = generateKeyPairSync("ed25519"); const wrong = generateKeyPairSync("ed25519"); expect(advancedAiAttestationCryptoFromEnv({})).toEqual({}); const env = { MENDPOINT_ATTESTATION_KEY_ID: "key-env", MENDPOINT_ATTESTATION_PRIVATE_KEY_PKCS8_BASE64: keys.privateKey.export({ format: "der", type: "pkcs8" }).toString("base64"), MENDPOINT_ATTESTATION_PUBLIC_KEY_SPKI_BASE64: keys.publicKey.export({ format: "der", type: "spki" }).toString("base64"), MENDPOINT_ATTESTATION_TENANT_IDS: "tenant-a", MENDPOINT_ATTESTATION_PRINCIPAL_ID: "actor", MENDPOINT_ATTESTATION_KEY_VALID_FROM: "2026-08-01T00:00:00.000Z", MENDPOINT_ATTESTATION_KEY_VALID_UNTIL: "2026-09-01T00:00:00.000Z" }; const crypto = advancedAiAttestationCryptoFromEnv(env); expect(crypto.signer?.keyId).toBe("key-env"); expect(crypto.attestationPrincipalId).toBe("actor"); expect(await crypto.trustPolicy?.resolve?.("key-env")).toMatchObject({ tenantIds: ["tenant-a"] }); expect(advancedAiAttestationCryptoFromEnv({ ...env, MENDPOINT_ATTESTATION_PUBLIC_KEY_SPKI_BASE64: wrong.publicKey.export({ format: "der", type: "spki" }).toString("base64") })).toEqual({}); });
  it("constructs a bound trainer only from complete env and performs no network at startup", async () => { const { db } = fixture(); let calls = 0; const receipt = { tenantId: "tenant-a", jobId: "job", requestDigest: "digest", leaseGeneration: 1, outcome: "pending", resultDigest: postTrainedReconciliationResultDigest({ status: "pending" }), observedAt: now, signature: "0".repeat(64) }; const transport = async (url: string | URL | Request, init?: RequestInit) => { calls++; const request = JSON.parse(String(init?.body)) as { jobId: string; requestDigest: string }; return new Response(JSON.stringify({ jobId: request.jobId, requestDigest: request.requestDigest, receipt, result: { status: "pending" } }), { status: 200, headers: { "content-type": "application/json" } }); }; expect(advancedAiTrainingRuntimeFromEnv(db, {}, transport as typeof fetch)).toEqual({}); const runtime = advancedAiTrainingRuntimeFromEnv(db, { MENDPOINT_POST_TRAINED_TRAINER_URL: "http://localhost:9999/trainer/", MENDPOINT_POST_TRAINED_TRAINER_TOKEN: "secret", MENDPOINT_POST_TRAINED_TRAINER_TIMEOUT_MS: "1000", MENDPOINT_POST_TRAINED_LEASE_MS: "5000", MENDPOINT_POST_TRAINED_WORKER_ID: "worker-1", MENDPOINT_POST_TRAINED_RECEIPT_HMAC_SECRET: "a".repeat(32), MENDPOINT_POST_TRAINED_EXTERNAL_PROCESSING_APPROVED: "1" }, transport as typeof fetch); expect(calls).toBe(0); expect(runtime.trainer).toBeDefined(); const result = await runtime.trainer!.train({ tenantId: "tenant-a", jobId: "job", adapterId: "adapter", requestDigest: "digest", leaseGeneration: 1, baseModelId: "base", corpus: [], recipe: { epochs: 1, maximumExamples: 1, seed: 1 }, signal: new AbortController().signal }); expect(result).toEqual({ receipt, result: { status: "pending" } }); expect(calls).toBe(1); });
  it("binds consent evidence to the dataset through the durable consent authority", () => {
    const { db } = fixture();
    db.raw.prepare("INSERT OR IGNORE INTO tenants (id, slug, name, created_at) VALUES (?, ?, ?, ?)").run("tenant-a", "tenant-a", "Tenant A", now);
    db.raw.prepare("INSERT INTO learning_dataset_versions (id, tenant_id, purpose, residency_region, version, temporal_cutoff_at, status, dataset_sha256, created_by_principal_id, sealed_by_principal_id, sealed_at, idempotency_key, request_fingerprint, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)").run("dataset-1", "tenant-a", "adapter_training", "local", 1, now, "sealed", "d".repeat(64), "actor", "actor", now, "dataset-idem", "e".repeat(64), now);
    db.raw.prepare("INSERT INTO learning_consents (id, tenant_id, consent_version, action, purpose, residency_region, authorized_by_principal_id, supersedes_consent_id, effective_at, expires_at, reason, idempotency_key, request_fingerprint, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)").run("consent-1", "tenant-a", 1, "granted", "adapter_training", "local", "actor", null, now, null, "approved", "consent-idem", "f".repeat(64), now);
    add(db, "consent-artifact", "learning_consent_evidence");
    insertEvidenceRecord(db, { id: "consent-evidence", tenantId: "tenant-a", subjectType: "learning_consent", subjectId: "consent-1", artifactId: "consent-artifact", producerPrincipalId: "actor", tool: "consent-authority", toolVersion: "1", verdict: "passed", createdAt: now });
    const verify = createDurablePostTrainedEvidenceAuthority(db);
    expect(verify("tenant-a", ["consent-evidence"], { subjectTypes: ["learning_consent"], subjectId: "dataset-1" })).toBe(true);
    expect(verify("tenant-a", ["consent-evidence"], { subjectTypes: ["learning_consent"], subjectId: "dataset-other" })).toBe(false);
    expect(verify("tenant-a", ["consent-evidence"], { subjectTypes: ["post_trained_training_job"], subjectId: "dataset-1" })).toBe(false);
  });
  it("requires tenant administration for issuance and adapter registration", async () => { const { app } = fixture(); const headers = { "content-type": "application/json", "idempotency-key": "denied", "x-role": "viewer" }; expect((await app.request("/advanced-ai/attestations", { method: "POST", headers, body: "{}" })).status).toBe(403); expect((await app.request("/advanced-ai/post-trained/adapters", { method: "POST", headers, body: "{}" })).status).toBe(403); });
  it("issues, retrieves and cryptographically verifies authoritative attestations", async () => { const { app, db } = fixture(); ["source", "snapshot", "candidate", "verification", "policy"].forEach((id) => add(db, id)); const issued = await app.request("/advanced-ai/attestations", { method: "POST", headers: { "content-type": "application/json", "idempotency-key": "attest-1" }, body: JSON.stringify({ repositoryId: "repo", runId: "run", correlationId: "corr", outcome: "passed", artifacts: { sourceIds: ["source"], snapshotId: "snapshot", candidateId: "candidate", verificationIds: ["verification"], policyId: "policy", deliveryId: null, rollbackId: null, waiverId: null } }) }); expect(issued.status).toBe(201); const value = await issued.json() as { attestationId: string }; expect((await app.request(`/advanced-ai/attestations/${value.attestationId}`)).status).toBe(200); const verified = await app.request(`/advanced-ai/attestations/${value.attestationId}/verify`, { method: "POST" }); expect(verified.status).toBe(200); expect(await verified.json()).toMatchObject({ verified: true, attestationId: value.attestationId }); expect((await app.request(`/advanced-ai/attestations/${value.attestationId}`, { headers: { "x-tenant": "tenant-b" } })).status).toBe(404); });
  it("registers only an exactly completed training artifact and exposes eligibility plus route dry run", async () => { const { app, db } = fixture(); add(db, "registration-corpus", "learning_dataset_corpus"); const trainedResponse = await app.request("/advanced-ai/post-trained/training-jobs", { method: "POST", headers: { "content-type": "application/json", "idempotency-key": "train-register" }, body: JSON.stringify({ jobId: "job-register", adapterId: "adapter-1", baseModelId: "base-1", datasetId: "dataset-1", purpose: "adapter_training", residencyRegion: "local", corpusArtifactIds: ["registration-corpus"], recipe: { epochs: 1, maximumExamples: 10, seed: 1 } }) }); const trained = await trainedResponse.json() as { adapterDigest: string; evaluation: AdapterLifecycleRecord["heldOutEvaluation"]; canary: AdapterLifecycleRecord["canaryEvidence"] }; expect(trainedResponse.status).toBe(201); const registered = await app.request("/advanced-ai/post-trained/adapters", { method: "POST", headers: { "content-type": "application/json", "idempotency-key": "register-1" }, body: JSON.stringify({ adapterId: "adapter-1", trainingJobId: "job-register", lifecycle: { ...lifecycle(), artifactDigest: trained.adapterDigest, heldOutEvaluation: trained.evaluation, canaryEvidence: trained.canary }, consent: consent(), descriptor: descriptor() }) }); expect(registered.status).toBe(201); expect(await (await app.request("/advanced-ai/post-trained/adapters/adapter-1")).json()).toMatchObject({ adapterId: "adapter-1", trainingJobId: "job-register", lifecycle: { state: "monitored" } }); const eligibility = await app.request("/advanced-ai/post-trained/adapters/adapter-1/eligibility", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ task: task() }) }); expect(await eligibility.json()).toMatchObject({ eligible: true, adapterId: "adapter-1" }); const dryRun = await app.request("/advanced-ai/post-trained/adapters/adapter-1/route-dry-run", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ task: task(), policy: policy(), remainingBudgetUsd: 1 }) }); expect(await dryRun.json()).toMatchObject({ action: "execute", dryRun: true, authorization: { authorized: true } }); expect((await app.request("/advanced-ai/post-trained/adapters/adapter-1", { headers: { "x-tenant": "tenant-b" } })).status).toBe(404); });
  it("runs a bounded local training fixture and exposes durable job status", async () => { const { app, db } = fixture(); add(db, "learning-corpus", "learning_dataset_corpus"); const response = await app.request("/advanced-ai/post-trained/training-jobs", { method: "POST", headers: { "content-type": "application/json", "idempotency-key": "train-1" }, body: JSON.stringify({ jobId: "job-1", adapterId: "adapter-1", baseModelId: "base-1", datasetId: "dataset-1", purpose: "adapter_training", residencyRegion: "local", corpusArtifactIds: ["learning-corpus"], recipe: { epochs: 1, maximumExamples: 10, seed: 1 } }) }); expect(response.status).toBe(201); expect(await response.json()).toMatchObject({ jobId: "job-1", status: "completed", adapterArtifactId: expect.stringMatching(/^artifact_/) }); expect(await (await app.request("/advanced-ai/post-trained/training-jobs/job-1")).json()).toMatchObject({ status: "completed" }); });
});
